spring:
  application:
    name: back

  datasource:
    url: jdbc:postgresql://localhost:5432/escoladanca
    username: postgres
    password: nicolasjp123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: esoladanca-2026-backend-jwt-secret-KEY-VERY-STRONG-256
  expiration: 7200000
